### ISSUE TITLE
Chromadb Implementation

### ISSUE THREAD

**Issue by shawnakumar** [jflachman/final_project#18]
1. 	ChromaDB Setup
2. 	Install ChromaDB and configure it for the project.
3. 	Embedding Generation (see Embedding task) 
4. 	Evaluate accessing Chromadb from Python or Url

**Comment by jflachman** [comment]
Completed the ChromaDB investigation and implementation in Docker with local persistence.

Test by adding a list of text documents to the DB, running a query and getting the two best resulting docs.

**Comment by jflachman** [comment]
The investigation is here: https://github.com/jflachman/local_rag_llm/tree/main/prototype/jeff/3-vectorDB
